In [4]:
import numpy as np 
import matplotlib.pyplot as plt 
import copy

# 1

In [205]:
def mulMatrices(m,v):
    r = np.zeros(shape=(len(m),len(v[0])))
    for i in range(len(m)):
        for j in range(len(v[0])):
            for k in range(len(m[0])):
                r[i][j] += m[i][k] * v[k][j]
    return r

a)

In [206]:
m = np.zeros([5,3])
m[0] = np.array([5,-4,-2])
m[1] = np.array([5,-5,4])
m[2] = np.array([2,5,-4])
m[3] = np.array([-5,4,3])
m[4] = np.array([3,-4,-3])

n = np.zeros([3,1])
n[0][0] = 5
n[1][0] = -2
n[2][0] = -3

mulMatrices(m,n)

array([[ 39.],
       [ 23.],
       [ 12.],
       [-42.],
       [ 32.]])

b) No se puede ya que la matriz no cumple las dimenciones para la multiplicacion

c) 

In [207]:
m = np.zeros([4,4])
m[0] = np.array([2,-5,5,1])
m[1] = np.array([5,2,-7,-6])
m[2] = np.array([-6,-1,7,-4])
m[3] = np.array([5,4,1,-5])

n = np.zeros([4,5])
n[0] = np.array([0,4,-7,1,-6])
n[0] = np.array([-1,-6,-5,1,1])
n[0] = np.array([2,-1,-6,5,-5])
n[0] = np.array([-3,-6,6,3,5])

mulMatrices(m,n)

array([[ -6., -12.,  12.,   6.,  10.],
       [-15., -30.,  30.,  15.,  25.],
       [ 18.,  36., -36., -18., -30.],
       [-15., -30.,  30.,  15.,  25.]])

# 2

In [208]:
def eliminacion_gaussiana(M, b):

    M = np.column_stack((M, b))
    n = len(M)
    m = len(M[0])

    for i in range(n):
        
        if M[i,i] == 0.:
            sub = copy.copy(M[n-1,:])
            M[n-1,:] = M[i,:]
            M[i,:] = sub
            
        M[i,:] /= M[i,i]
        
        for j in range(i+1,n):
            if M[j,i] == 0.: 
                sub = copy.copy(M[n-1,:])
                M[n-1,:] = M[j,:]
                M[j,:] = sub

                
            val = float(M[j,i]/M[i,i])
            
            for k in range(i,m):
                M[j,k] -= val*M[i,k]           
                
    bFinal = M[:,n]
    
    return M,bFinal

def substitution(M, b):
    
    n = np.shape(M)[0]

    v = np.zeros(n)

    for i in range(n-1,-1,-1):
        sum = b[i]
        for j in range(n-1,i,-1):
            sum -= M[i,j]*v[j]
        v[i] = sum/M[i,i]

    return v

a)

In [209]:
A1 = np.array([[3.,1.,-1.],\
             [1.,-2.,1.],
             [4.,-1.,1.]])
b1 = np.array([2.,0.,3.])

M,b = eliminacion_gaussiana(A1,b1)
back_substitution(M,b)

array([0.71428571, 0.85714286, 1.        ])

b)

In [210]:
A1 = np.array([[1.,1.,1.],\
             [0.,-8.,10.],
             [4.,-8.,0.]])
b1 = np.array([0.,0.,6.])

M,b = eliminacion_gaussiana(A1,b1)
back_substitution(M,b)

array([ 0.71052632, -0.39473684, -0.31578947])

# 3

In [1]:
def initialize(m1,m2,m3, k11,k12, k13, k21,k22,k23, k31,k32,k33):
    matriz= np.array([[k11/m1, k12/m1, k13/m1], [k21/m2, k22/m2, k23/m2], [k31/m3, k32/m3, k33/m3]])

    return  matriz

In [2]:
def power_method( matriz, iterations=10000, tolerancia= 1e-10):

    eigenvector= np.ones(3)
    error=float('inf')
    vector= np.ones(3)
    i=0
    while error> tolerancia and i< iterations:

        matrix_v= (np.dot(matriz, eigenvector))
        eigenvalue= np.dot(eigenvector, matrix_v)
        eigenvector= matrix_v/np.linalg.norm(matrix_v)
        vector= eigenvector* np.linalg.norm(matrix_v)

        if i> 0:
            error= np.abs((eigenvalue- valor)/ valor)

        valor= eigenvalue
        i+=1
    
    return eigenvalue, vector

In [5]:
m1=m2=m3= 1
k=1

k11=k22=k33=-2*k
k12=k21=k23=k32=k
k13=k31=0

matrix= initialize(m1,m2,m3, k11,k12, k13, k21,k22,k23, k31,k32,k33)
invmatrix=np.linalg.inv(matrix)

max_eigenvalue,max_eigenvector= power_method(matrix)
max_eigenvector= np.dot(invmatrix, max_eigenvector)
min_eigenvalue,min_eigenvector= power_method(invmatrix)
min_eigenvalue= 1/min_eigenvalue
min_eigenvector= np.dot(matrix, min_eigenvector)

max_frecuency= np.sqrt((-1)*max_eigenvalue)
min_frecuency= np.sqrt((-1)*min_eigenvalue)

print("k=", k)
print(matrix)
print("Max eigenvlue", max_eigenvalue)
print("Max eigenvector", max_eigenvector)
print("Min eigenvlue", min_eigenvalue)
print("Min eigenvector", min_eigenvector)
print("Max frecuency", max_frecuency)
print("Min frecuency", min_frecuency)

k= 1
[[-2.  1.  0.]
 [ 1. -2.  1.]
 [ 0.  1. -2.]]
Max eigenvlue -1.9999999999999996
Max eigenvector [-7.07106781e-01  1.57009246e-16 -7.07106781e-01]
Min eigenvlue -0.5857864376271786
Min eigenvector [-0.50000038 -0.70710625 -0.50000038]
Max frecuency 1.414213562373095
Min frecuency 0.7653668647303583
